### PR TITLE
GEOMESA-2679 Infer encoding of shapefile from cpg file

### PR DESCRIPTION
**Pull request by Kontinuation**
Added shapefiles with UTF-8 encoding for testing. These newly added shapefiles were taken from the OpenStreetMap project.

### CODE REVIEW

**Review by elahrvivaz — APPROVED** [review]

**Comment by elahrvivaz** [comment]
@jnh5y are there any license issues with including OSM files in tests? They appear to be ODBL licensed: https://opendatacommons.org/licenses/odbl/summary/

**Comment by jnh5y** [comment]
> @jnh5y are there any license issues with including OSM files in tests? They appear to be ODBL licensed: https://opendatacommons.org/licenses/odbl/summary/

I do not know.  I believe the ODBL is "copy left"; I will ask Eclipse.  

@Kontinuation sorry for the delay.

One option would be to ship the code changes *now* and put up the unit tests as a separate PR.  That would allow us to have working code today and maybe later have a regression test to ensure that a future change doesn't cause trouble.

**Comment by elahrvivaz** [comment]
Sounds like the licenses are ok, based on https://www.eclipse.org/org/foundation/boardminutes/2018_06_11-12_Minutes.pdf
@jnh5y have you had a chance to review and/or are you ok with me merging?

**Comment by elahrvivaz** [comment]
I guess I spoke prematurely. We need to file a CQ for this I guess. I'll do that.

**Comment by elahrvivaz** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23602

**Comment by elahrvivaz** [comment]
@Kontinuation could you please add the following snippet to the end of LICENSES.md?
```
### OpenStreetMap

GeoMesa includes some shapefiles from the OpenStreetMap project. These files are licensed under the
[Open Data Commons Open Database License](https://opendatacommons.org/licenses/odbl/summary/).
```

**Review by elahrvivaz — CHANGES_REQUESTED** [review]
Please add the license to LICENSES.md as mentioned just above.

**Review by elahrvivaz — APPROVED** [review]

**Comment by elahrvivaz** [comment]
thanks! just waiting on the cq from eclipse now...

**Comment by elahrvivaz** [comment]
cqs approved!

**Pull request merged**
