### PR TITLE
GEOMESA-964 Exposing java api for KyroFeatureSerializer

### PR DESCRIPTION
**Pull request by Afterglow375**
Signed-off-by: Alex Tatusko <atatusko@ccri.com>

### CODE REVIEW

**Comment by cne1x** [comment]
Travis is right:  This PR does not build:

**Comment by cne1x** [comment]
@Afterglow375 Travis is right; this PR does not build:

```
[error] /opt/devel/src/geomesa/geomesa-features/geomesa-feature-common/src/main/java/org/locationtech/geomesa/features/interop/SerializationOptions.java:15: error: incompatible types: Set cannot be converted to SerializationOptions
[error]         return SerializationOption.SerializationOptions$.MODULE$.withUserData();
```

**Comment by jahhulbert-ccri** [comment]
can we get a junit test in src/test/java that shows how to use this java api and make sure it looks pretty

**Comment by anthonyccri** [comment]
@Afterglow375 this is still failing the build.  

```
[info] Compiling 6 Scala sources and 1 Java source to /opt/devel/src/geomesa/geomesa-features/geomesa-feature-kryo/target/test-classes...
[error] /opt/devel/src/geomesa/geomesa-features/geomesa-feature-kryo/src/test/java/org/locationtech/geomesa/features/interop/SerializationOptionsTest.java:34: error: incompatible types: SerializationOptions cannot be converted to Set
[error]         KryoFeatureSerializer serializer = new KryoFeatureSerializer(sft, SerializationOptions.withUserData());
[error]                                                                                                            ^
[error] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
```

**Comment by elahrvivaz** [comment]
closing in favor of https://github.com/locationtech/geomesa/pull/770

**Pull request closed without merging**
