### PR TITLE
GEOMESA-2517 HBase - fix spark-sql projections with remote-filtering disabled

### PR DESCRIPTION
**Pull request by misslzyan**
…nstance to deserialize the encoded byte data

fix bug :
  when use spark-sql specified the fields   for querying data from hbase data ,the wrong deserializer can't deserialize the encoded byte data .
  change it with ProjectingKryoFeatureDeserializer . fix it .

### CODE REVIEW

**Comment by elahrvivaz** [comment]
Are you seeing an issue with 'remoteFilters' disabled? I don't believe that this fix would work with remote filters

**Comment by misslzyan** [comment]
> Are you seeing an issue with 'remoteFilters' disabled? I don't believe that this fix would work with remote filters

Please show the issue. I have not seen the issue. I just test the code with the remoteFilters disabled.

**Comment by elahrvivaz** [comment]
yes, this change has broken a lot of unit tests in the CI build. Is it correct that you are using `hbase.remote.filtering = false`?

**Comment by misslzyan** [comment]
> yes, this change has broken a lot of unit tests in the CI build. Is it correct that you are using `hbase.remote.filtering = false`?

yes. Just because I havn't replace the bug-fix  code on the cluster ,so I just use the `hbase.remote.filtering = false` as a test .

**Comment by elahrvivaz** [comment]
Thanks, I updated the ticket title. I think to fix the issue you are going to have to modify the `org.locationtech.geomesa.hbase.jobs.GeoMesaHBaseInputFormat` and/or `org.locationtech.geomesa.spark.hbase.HBaseSpatialRDDProvider`

**Comment by misslzyan** [comment]
@elahrvivaz   I'm new to geomesa . and also I'm new to be a contributor .   I do the commit also have some problems with checks fail.  I'm so sorry.

**Comment by misslzyan** [comment]
> Thanks, I updated the ticket title. I think to fix the issue you are going to have to modify the `org.locationtech.geomesa.hbase.jobs.GeoMesaHBaseInputFormat` and/or `org.locationtech.geomesa.spark.hbase.HBaseSpatialRDDProvider`

Thank you for telling me that . I will do it tomorrow because the time is 00:02AM . I shoud go to bed .

**Comment by elahrvivaz** [comment]
No problem - thanks for contributing. You'll need to sign the eclipse contributor agreement to pass validation, as detailed here: https://github.com/locationtech/geomesa/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by elahrvivaz** [comment]
@misslzyan I'm going to close this for now, but feel free to re-open if you work on it again. Thanks!

**Pull request closed without merging**
