### PR TITLE
GEOMESA-1472 Transformers functionMap needs to be synchronized

### PR DESCRIPTION
**Pull request by anthonyccri**
Signed-off-by: Anthony Fox <anthonyfox@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
@anthonyccri is it possible to get a unit test for this?  If not, that's fine.

**Comment by anthonyccri** [comment]
It would be more trouble than its worth to unit test it.

**Comment by elahrvivaz** [comment]
just curious what problem this is fixing - since it's an object, i didn't think it would need to be synchronized?

**Comment by anthonyccri** [comment]
There's a race condition in initializing the map.  There's the declaration and then there's the initialization.  I was loading up multiple converters in the same JVM and was seeing some cases in which the map was empty and throwing lots of errors.

**Comment by elahrvivaz** [comment]
weird, i thought that the object couldn't be accessed until it had 'initialized'... we probably have a lot of other places this might be an issue too

**Comment by jnh5y** [comment]
Since functionMap is a lazy val, it is null until the Transformers object is initialized. 

I'm fine with this change...

**Pull request merged**
