### PR TITLE
GEOMESA-843 Enable Zinc compilation

### PR DESCRIPTION
**Pull request by jnh5y**
For information about using Zinc, check out https://github.com/typesafehub/zinc.
You must run a Zinc server separately to see the speed up, but this is optional.

Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by anthonyccri** [comment]
Local build is failing for me.  Seems like a unit test in geomesa-jobs is failing?

**Comment by elahrvivaz** [comment]
Could we make this a profile so that a build doesn't require installation of more dependencies? Some environments might not have zinc available. Although that might introduce subtle inconsistencies if the compiler result differs at all b/t zinc and non-zinc...

**Comment by elahrvivaz** [comment]
@jnh5y any thoughts to making zinc compilation enabled via profile?

**Comment by elahrvivaz** [comment]
merged as a4292a49e69fadf51ab0e2fc0e40b8b9ef76087d

**Pull request closed without merging**
