### PR TITLE
GEOMESA-2596 fix SparkUtils#row2Sf. convert sql.Date to util.Date

### PR DESCRIPTION
**Pull request by misslzyan**
fix it . 

Signed-off-by: 段卫东 <misslzyan108@gmail.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
@misslzyan I just force-pushed master to fix a recent commit, could you rebase this on the updated master? sorry about that.

**Comment by elahrvivaz** [comment]
@misslzyan grepping through our code, there are a lot of places that we call `.toInstant`. I was unaware that `java.sql.Date` overrode that method. Possibly it would be better to replace our usages of `.toInstant` with `Instant.ofEpochMillis`?

**Comment by misslzyan** [comment]
ok，agree with you, I will do it latter 


| |
dean
|
|
邮箱：13552627021@163.com
|

Signature is customized by Netease Mail Master

On 03/28/2019 20:27, Emilio wrote:

@misslzyan I just force-pushed master to fix a recent commit, could you rebase this on the updated master? sorry about that.

**Comment by misslzyan** [comment]
how to change the code easily by doing this “

Possibly it would be better to replace our usages of .toInstant with Instant.ofEpochMillis?

“,please give me suggestion^_^
| |
dean
|
|
邮箱：13552627021@163.com
|

Signature is customized by Netease Mail Master

On 03/28/2019 20:38, Emilio wrote:

@misslzyan grepping through our code, there are a lot of places that we call .toInstant. I was unaware that java.sql.Date overrode that method. Possibly it would be better to replace our usages of .toInstant with Instant.ofEpochMillis?

**Comment by elahrvivaz** [comment]
I think most of the places we use `.toInstant`, we are converting a `java.util.Date` to a `ZonedDateTime`. The implementation of `.toInstant` in `java.util.Date` is just `Instant.ofEpochMilli(getTime())`. We could add a little utility method that converts a date to a `ZonedDateTime`, and then replace our calls of `.toInstant` with the utility method. We'd could use `git grep toInstant` or the 'usages' search in intellij to identify the places we call it.

**Comment by misslzyan** [comment]
Got it. Thank you very much !

**Comment by misslzyan** [comment]
@elahrvivaz done. You check it please .

**Pull request merged**
