### PR TITLE
GEOMESA-2977 Option to query z-filters in 1.3 Accumulo installs

### PR DESCRIPTION
**Pull request by elahrvivaz**
* Use QueryHints.FILTER_COMPAT = "1.3"
* Supports basic non-strict date time queries against z3 index
* Supports basic queries against xz3 index
* Does not support transforms or advanced queries

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
Ok, so the z2 index is not supported, right?  

How hard would it be to throw an exception for non-supported combinations?

**Comment by jnh5y** [comment]
Would it be worth adding an optional bit to the Query Explainer output to show that a back compatible scan is being run?

**Comment by jnh5y** [comment]
If we were gonna be nice, I could imagine running the remote version code during DataStore creation and automatically setting the hint:).  *shrugs*  That's probably a ton of work going forward.

**Comment by elahrvivaz** [comment]
> If we were gonna be nice, I could imagine running the remote version code during DataStore creation and automatically setting the hint:). _shrugs_ That's probably a ton of work going forward.

Unfortunately getting the remote version is kind of slow... we used to load it up when creating a data store but now it's lazily done I think. but i think we'd have to provide better back-compatibility support than this to justify that.

**Comment by elahrvivaz** [comment]
> Ok, so the z2 index is not supported, right?
> 
> How hard would it be to throw an exception for non-supported combinations?

Across all data stores, or just Accumulo? it would be a lot of checks...

**Pull request merged**
