### PR TITLE
GEOMESA-948 Fixing renaming transformations

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
looks good. @elahrvivaz does this help with https://github.com/locationtech/geomesa/pull/712 ?

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri yeah, i think this will allow 712 to work.

**Comment by jdk2pq** [comment]
Tested and worked for me! Fixed #712 as well.

**Comment by jahhulbert-ccri** [comment]
@jdk2pq i'll merge this one in...then you can rebase/merge #712

**Comment by jahhulbert-ccri** [comment]
8ab174450c37a3b63362805b8f4831e8a19bf3cc

**Pull request closed without merging**
