### PR TITLE
GEOMESA-643 Exclude Yammer

### PR DESCRIPTION
**Pull request by mm64z**
yammer.metrics is excluded from kafka

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
12f8f0a57c000d577a8b295b8a5430ed03b84507

**Comment by jahhulbert-ccri** [comment]
@mm64z see comments in https://geomesa.atlassian.net/browse/GEOMESA-643 I reopened the PR

**Comment by elahrvivaz** [comment]
Bad news: the kafka data store doesn't work without metrics. Can't read or write features.

**Comment by jnh5y** [comment]
I've requested that Kafka (and this dependency) be considered for 'works with' status.  If that happens, we will change these to provided dependencies and this PR will be OBE.

**Comment by jnh5y** [comment]
I'm closing this PR.  Either Kafka will be 'works with' or this ticket would break the Kafka DataStore.  

Either way, we won't be merging this code.

**Pull request closed without merging**
