### PR TITLE
1.2.x GEOMESA-1609 Configurable Cleanup Cache Interval for KafkaDataStore

### PR DESCRIPTION
**Pull request by aheyne**
Signed-off-by: Austin Heyne <aheyne@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
@aheyne travis build is failing due to license headers

**Comment by elahrvivaz** [comment]
@aheyne does this need to got into an urgent bug fix (e.g. 1.2.7.4), or is it ok for 1.2.8? Either way, please open a new PR against the `1.2` branch (and close this one if we don't need it for 1.2.7.4).

**Comment by elahrvivaz** [comment]
looks good

**Comment by aheyne** [comment]
Moved to #1345

**Pull request closed without merging**
