### PR TITLE
GEOMESA-1915 ViewParams - using reflection to avoid specifying each QueryHint

### PR DESCRIPTION
**Pull request by elahrvivaz**
* Note: removes 'STRATEGY' as an alias for 'QUERY_INDEX'

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
I like it.  Any risk in shipping it in 1.3.2?

**Comment by elahrvivaz** [comment]
probably could ship it - I removed the 'STRATEGY' alias so we would just need to make sure clients aren't still using that (replaced with 'QUERY_INDEX')

**Comment by jnh5y** [comment]
In terms of STRATEGY, etc what shipped in 1.3.1?  I wonder if we should take some care to be compatible, etc?

**Comment by elahrvivaz** [comment]
we've supported strategy going back to the original implementation (1.2.0?) -it's technically been deprecated but probably not marked as such.

**Comment by elahrvivaz** [comment]
since i don't think we're going to be adding any more query hints in 1.3.2, there's not much upside to merging this until 1.3.3/1.4.0

**Pull request merged**
