### PR TITLE
GEOMESA-2417 - FSDS - Classpath issue with orc+hive in spark-runtime jar

### PR DESCRIPTION
**Pull request by jnh5y**

### CODE REVIEW

**Comment by elahrvivaz** [comment]
nice find. looks good, do we need to run the cq script?

**Comment by jnh5y** [comment]
Good call.  Doing that now.....

**Comment by elahrvivaz** [comment]
did the build pass the first time? I'll merge if so, if we're not sure I'll wait for travis. @jnh5y I'll add a sign-off by you, if that's ok

**Comment by jnh5y** [comment]
@elahrvivaz it looks like it did build both times.  Feel free to add the sign-off and shippit!

**Pull request merged**
