### PR TITLE
GEOMESA-1454 Add SFT name getter to GenerateFeatureWrappers

### PR DESCRIPTION
**Pull request by vpipkt**
Method in generated wrapper is called `getSimpleFeatureTypeName`, which is unlikely to be the name of an attribute on a simple feature.

Signed-off-by: Jason T. Brown <jason.brown@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
looks good - you know you can do feature.getSimpleFeatureType.getTypeName, right? ;)

**Comment by vpipkt** [comment]
@elahrvivaz of course. But there are cases where we are working with the simple feature type and have no simple feature objects. E.g. we are doing a simple feature builder, and need to the sft name to intialize it...

**Comment by elahrvivaz** [comment]
doesn't the implicit value class require a SimpleFeature instance though?

**Comment by vpipkt** [comment]
@elahrvivaz great point. This Maybe what I am after in the output is more like this:

```
object SimpleFeatureWrappers {

  val test1 = "test1"

  implicit class test1(val sf: org.opengis.feature.simple.SimpleFeature) extends AnyVal {
  //...
  }
}
```

And then could use SimpleFeatureWrappers.test1 instead of "test1"

**Comment by elahrvivaz** [comment]
yeah, that would make sense

**Comment by jnh5y** [comment]
@elahrvivaz @vpipkt Are you guys good with this PR?

**Comment by elahrvivaz** [comment]
I don't think it does what @vpipkt actually wanted - might want to hold off

**Comment by elahrvivaz** [comment]
@vpipkt going to close this as I think you decided you didn't want it - let me know if otherwise.

**Pull request closed without merging**
