### PR TITLE
GEOMESA-1397 GeoHashUtils.getInternationalDateLineSafeGeometry return…

### PR DESCRIPTION
**Pull request by elahrvivaz**
…s Try[Geometry]

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
Does this sort out by @ddseapy?;)

**Comment by elahrvivaz** [comment]
yep, he's happy

**Comment by jnh5y** [comment]
:shipit:!

**Comment by jnh5y** [comment]
As one final question/note, do we need to sort out a 1.2.x backport?

**Comment by ddseapy** [comment]
Not necessary for me, i don't think  (if that question was for me).

**Comment by elahrvivaz** [comment]
yeah, i think we held off on changing this before to preserve the API in 1.2.x - so no backport necessary.

**Pull request merged**
