### PR TITLE
GEOMESA-991 Fixing explain logging indentation

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
nice :+1:  i'm glad you actually added some real indent instead of my \t dotted randomly!

**Comment by jahhulbert-ccri** [comment]
looks good...built and tested and got some output...here's a sample for anyone who wants to see:
```
Planning 'twitter' ((user_name IN ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17')) AND (dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00)) AND BBOX(geom, 40.0,40.0,50.0,50.0)
  Hints: density false, bin false
  Transforms: None
  Sort: none
  Strategy selection:
    Filter plan selected: FilterPlan[ATTRIBUTE[user_name = '17' OR user_name = '16' OR user_name = '15' OR user_name = '14' OR user_name = '13' OR user_name = '12' OR user_name = '11' OR user_name = '10' OR user_name = '9' OR user_name = '8' OR user_name = '7' OR user_name = '6' OR user_name = '5' OR user_name = '4' OR user_name = '3' OR user_name = '2' OR user_name = '1'][dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00 AND BBOX(geom, 40.0,40.0,50.0,50.0)]] (Cost 26)
    Filter plans not used (1): FilterPlan[Z3[BBOX(geom, 40.0,40.0,50.0,50.0) AND dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00][user_name IN ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17')]] (Cost 200)
    Strategy selection took 20ms for 2 options
  Strategy 1 of 1: AttributeIdxStrategy
    Strategy filter: ATTRIBUTE[user_name = '17' OR user_name = '16' OR user_name = '15' OR user_name = '14' OR user_name = '13' OR user_name = '12' OR user_name = '11' OR user_name = '10' OR user_name = '9' OR user_name = '8' OR user_name = '7' OR user_name = '6' OR user_name = '5' OR user_name = '4' OR user_name = '3' OR user_name = '2' OR user_name = '1'][dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00 AND BBOX(geom, 40.0,40.0,50.0,50.0)]
  Plan: org.locationtech.geomesa.accumulo.index.JoinPlan
    Table: mycatalog_attr_idx
    Deduplicate: false
    Column Families: all 
    Ranges (17): [%01;%00;%01;17%00;80000143503f::%01;%00;%01;17%00;800001435567%00;), [%01;%00;%01;16%00;80000143503f::%01;%00;%01;16%00;800001435567%00;), [%01;%00;%01;15%00;80000143503f::%01;%00;%01;15%00;800001435567%00;), [%01;%00;%01;14%00;80000143503f::%01;%00;%01;14%00;800001435567%00;), [%01;%00;%01;13%00;80000143503f::%01;%00;%01;13%00;800001435567%00;)
    Iterators (1): [name:filter-transform-iter, priority:25, class:org.locationtech.geomesa.accumulo.iterators.KryoLazyFilterTransformIterator, properties:{sft=dtg:Date,*geom:Point:srid=4326:index=full:index-value=true, cql=BBOX(geom, 40.0,40.0,50.0,50.0) AND dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00}]
    Join plan:
    Plan: org.locationtech.geomesa.accumulo.index.BatchScanPlan
      Table: mycatalog_records
      Deduplicate: false
      Column Families: all 
      Ranges (1): [-inf::+inf]
      Iterators (0): []
  Query planning took 80ms
```

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri That join plan indent looks off actually, let me fix that too. I like the idea of new lines for iterators and filter plans - for ranges i think there would be too many to be feasible, and the idea is just to give you a sense of what you've got, so i'd rather not do it there.

**Comment by jahhulbert-ccri** [comment]
sounds good. yeah i'm sure we could always add some json/xml representation or export format or something if we needed it.

**Comment by jahhulbert-ccri** [comment]
looks good...anybody else have comments?

```
Planning 'twitter' ((user_name IN ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17')) AND (dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00)) AND BBOX(geom, 40.0,40.0,50.0,50.0)
  Hints: density false, bin false
  Transforms: None
  Sort: none
  Strategy selection:
    Filter plan selected: FilterPlan[ATTRIBUTE[user_name = '17' OR user_name = '16' OR user_name = '15' OR user_name = '14' OR user_name = '13' OR user_name = '12' OR user_name = '11' OR user_name = '10' OR user_name = '9' OR user_name = '8' OR user_name = '7' OR user_name = '6' OR user_name = '5' OR user_name = '4' OR user_name = '3' OR user_name = '2' OR user_name = '1'][dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00 AND BBOX(geom, 40.0,40.0,50.0,50.0)]] (Cost 26)
    Filter plans not used (1):
      FilterPlan[Z3[BBOX(geom, 40.0,40.0,50.0,50.0) AND dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00][user_name IN ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17')]] (Cost 200)
    Strategy selection took 20ms for 2 options
  Strategy 1 of 1: AttributeIdxStrategy
    Strategy filter: ATTRIBUTE[user_name = '17' OR user_name = '16' OR user_name = '15' OR user_name = '14' OR user_name = '13' OR user_name = '12' OR user_name = '11' OR user_name = '10' OR user_name = '9' OR user_name = '8' OR user_name = '7' OR user_name = '6' OR user_name = '5' OR user_name = '4' OR user_name = '3' OR user_name = '2' OR user_name = '1'][dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00 AND BBOX(geom, 40.0,40.0,50.0,50.0)]
  Plan: org.locationtech.geomesa.accumulo.index.JoinPlan
    Table: mycatalog_attr_idx
    Deduplicate: false
    Column Families: all 
    Ranges (17): [%01;%00;%01;17%00;80000143503f::%01;%00;%01;17%00;800001435567%00;), [%01;%00;%01;16%00;80000143503f::%01;%00;%01;16%00;800001435567%00;), [%01;%00;%01;15%00;80000143503f::%01;%00;%01;15%00;800001435567%00;), [%01;%00;%01;14%00;80000143503f::%01;%00;%01;14%00;800001435567%00;), [%01;%00;%01;13%00;80000143503f::%01;%00;%01;13%00;800001435567%00;)
    Iterators (1):
      name:filter-transform-iter, priority:25, class:org.locationtech.geomesa.accumulo.iterators.KryoLazyFilterTransformIterator, properties:{sft=dtg:Date,*geom:Point:srid=4326:index=full:index-value=true, cql=BBOX(geom, 40.0,40.0,50.0,50.0) AND dtg AFTER 2014-01-02T00:00:00+00:00 AND dtg BEFORE 2014-01-03T00:00:00+00:00}
    Join Plan: org.locationtech.geomesa.accumulo.index.BatchScanPlan
      Table: mycatalog_records
      Deduplicate: false
      Column Families: all 
      Ranges (1): [-inf::+inf]
      Iterators (0):
  Query planning took 74ms
```

**Comment by jahhulbert-ccri** [comment]
3174ad8ed4467168ae0b86c2da0424a790c170e2

**Pull request closed without merging**
