### PR TITLE
GEOMESA-3250 Support for Scala 2.13

### PR DESCRIPTION
**Pull request by elahrvivaz**
* Bundle sfcurve classes as there is no 2.13 dependency available
* Remove various unused GeoHash and util classes
* Replace .par calls with explicit thread pools
* Add .toSeq for Scala 2.13 default Seq import change
* Update CloseableIterator for Scala 2.13 API changes
* Add Scala 2.13 GitHub build
* Kryo 3.0.3 -> 4.0.2
* Pureconfig 0.11.1 -> 0.17.2
* Scala-logging 3.8.0 -> 3.9.5
* Apache Orc 1.8.0 -> 1.8.1
* Json4s 3.5.4 -> 3.6.12

### CODE REVIEW

**Comment by pashashiz** [comment]
Awesome news. I was actually doing the same and came a bit late, yet looks like I updated way more libraries https://github.com/pashashiz/geomesa/pull/5 ;)

**Comment by pashashiz** [comment]
Oh, I see now, you used `locationtech:4_0_0` branch. Do you guys have any target date to release `4.0` version?

**Comment by elahrvivaz** [comment]
> Awesome news. I was actually doing the same and came a bit late, yet looks like I updated way more libraries [pashashiz#5](https://github.com/pashashiz/geomesa/pull/5) ;)

ah, nice - we're still cross-compiling with scala 2.12, so we didn't go as far as it looks like you did with all the 2.13 updates as some of them aren't back-compatible

**Comment by elahrvivaz** [comment]
> Oh, I see now, you used `locationtech:4_0_0` branch. Do you guys have any target date to release `4.0` version?

We don't, currently... I'm hoping in the next month or so.

**Pull request merged**
