### PR TITLE
GEOMESA-2113 Upgrade Arrow to 0.9

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

TODO:
- [ ] update to arrow version with bugfix
- [ ] open cqs
- [ ] update arrow sample files checked into test directory with new IPC format

### CODE REVIEW

**Comment by elahrvivaz** [comment]
Found a bug in arrow that will need to be fixed before this can be merged: https://issues.apache.org/jira/browse/ARROW-2500
Since that will require new cqs, will need to file those afterwards.

**Comment by elahrvivaz** [comment]
- [ ] update to arrow version with bugfix
- [ ] open cqs
- [ ] update arrow sample files checked into test directory with new IPC format

**Comment by jahhulbert-ccri** [comment]
@elahrvivaz could we have an arrow09 mime type?

**Comment by jahhulbert-ccri** [comment]
ah its not backwards compat at all :( sad

**Comment by elahrvivaz** [comment]
bhulette said that the javascript impl seemed to work with different versions, so I'm going to look into it some more. But I tried with a 0.6 distributed runtime and 0.9 client and it threw an arrow message serialization exception. Since they haven't released 1.0 yet, they're not focusing on back-compatibility.

**Comment by elahrvivaz** [comment]
There is an arrow PR up [here](https://github.com/apache/arrow/pull/2008) that fixes the bug. Tests passed with that branch. It should be available in arrow 0.10

**Comment by elahrvivaz** [comment]
replaced with https://github.com/locationtech/geomesa/pull/2018

**Pull request closed without merging**
