### PR TITLE
GEOMESA-1499,GEOMESA-2038 Download script improvements

### PR DESCRIPTION
**Pull request by elahrvivaz**
* Allows override of maven server via GEOMESA_MAVEN_URL env variable
* Uses `curl` instead of `wget`
* Moves download code into common function
* Lists jars being downloaded before confirming
* Downloads up to 4 jars simultaneously using xargs
* Defaults to GEOMESA_XX_HOME/lib as the download location
* Removes ability to specify versions on the command line - must edit files instead

Note: requires at least v1.1.0 of 'sphinx_tabs' installed to build docs

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
@jahhulbert-ccri do you want to review this?

**Comment by jnh5y** [comment]
@elahrvivaz this has merge conflicts now...  @jahhulbert-ccri any interest in reviewing?  If not, I can skim and merge once the conflicts are sorted out.

**Comment by elahrvivaz** [comment]
fixed conflicts, thanks

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri should probably review if he has time, this is based on tickets he opened so it'd be good if he verified it's what he wants.

**Comment by jnh5y** [comment]
Carp, more conflicts.  And yes, I am fine with @jahhulbert-ccri reviewing.  Sounded like he'd have some time over the holidays.

**Comment by elahrvivaz** [comment]
fixed conflicts

**Pull request merged**
