### PR TITLE
GEOMESA-1963 Combining convert modules

### PR DESCRIPTION
**Pull request by elahrvivaz**
* New merged module is geomesa-convert-core, replaces geomesa-convert-all and all other individual modules except osm

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
should i bother to rebase this, or do we want to keep the modules separate? either way is fine with me...

**Comment by jahhulbert-ccri** [comment]
i'll look again.

**Comment by anthonyccri** [comment]
I think I'd prefer not to combine all of these.  Can't you use the `geomesa-convert-all_2.11` module if you want to bring in everything?  I like having these separate so we can limit the transitive dependency impact.

**Comment by elahrvivaz** [comment]
closing as won't fix

**Pull request closed without merging**
