### PR TITLE
GEOMESA-1449 GeoJson Support

### PR DESCRIPTION
**Pull request by elahrvivaz**
~~note: stacks on top of #1102~~

* New module geomesa-geojson
* Scala API - GeoJsonIndex/GeoJsonGtIndex
* Rest API - GeoJsonServlet

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
CQ approvals required transitively from #1102

**Comment by jnh5y** [comment]
@mdzimmerman @cfkelly can you stand up the REST API and see if you can make it go?

**Comment by jahhulbert-ccri** [comment]
so far looks pretty cool gonna look over it tomorrow. @elahrvivaz can you rebase it again? i'll give it a run in the mornin

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri rebased

**Comment by elahrvivaz** [comment]
yeah [GEOMESA-1457](https://geomesa.atlassian.net/browse/GEOMESA-1457)

**Pull request merged**
