### PR TITLE
GEOMESA-1299 Better back-compatibility tests

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
question: do we care about things before 1.1.0-rc7?

**Comment by jahhulbert-ccri** [comment]
good question...i think we may have schemas from rc7 and tables from rc6 that we need to support or else have a well tested transition to the new schemas using the copy job.

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri you mean 1.0.0-rc6 and 7? I'll add those.

**Comment by jahhulbert-ccri** [comment]
i think 1.1.0-rc6 is as far back as we have supported or might support recently

**Comment by elahrvivaz** [comment]
ok, cool - I'll just add rc6 then

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri added 1.1.0-rc.6

**Pull request merged**
