### PR TITLE
GEOMESA-2834 Deserialize using 3 dimensions for 3D support in Spark JTS

### PR DESCRIPTION
**Pull request by netanel246**
* WKBWriter writes 3 dimensions in order to support 3 dimensions geometries while deserialize

* Added test

Signed-off-by: netanel246 <netanel246@gmail.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
we should probably add this to the other WKBUtils class in the geomesa-utils module, but that doesn't need to be part of this PR.

**Comment by elahrvivaz** [comment]
@jnh5y i'm planning to merge this today, let me know if you object.

**Comment by jnh5y** [comment]
> @jnh5y i'm planning to merge this today, let me know if you object.

@elahrvivaz can I have one more day to think on it?  (I want to at least enter a GeoMesa ticket about the follow-on for post 3.0.)

**Comment by elahrvivaz** [comment]
merged as dcf0fc89fcf69ea7c2395ec5d3ff681c726b94b4. thanks!

**Pull request closed without merging**
