### PR TITLE
GEOMESA-1834 - Enable experimental Maven Incremental Module Build

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
if you don't specify `-b incremental`, will it change the build at all? just want to verify we can still build the 'old fashioned' way if need be.

**Comment by jnh5y** [comment]
If you don't add '-b incremental', the build is the same as ever.  You have to read the manual and purposefully try the new thing.

**Comment by jahhulbert-ccri** [comment]
prob going to close and not merge...figure for CI we want a fresh build each time.

**Comment by jahhulbert-ccri** [comment]
holding off for now will open later if desired.

**Pull request closed without merging**
