### PR TITLE
GEOMESA-1040 Adding progress to converter input formats

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
looking good...about to build and test it out myself..

@elahrvivaz i wonder if long term we could add code that would print out the % done to the command line...or enable logging for that from the MR framework since it logs it usually.

Follow-on ticket would be ok...but now that we have some counters we could probably display some progress to the user somehow so they know it isn't dead...

also we should print out the job tracking URL in the logging.

this might just be log4j config of hadoop classes

**Comment by jahhulbert-ccri** [comment]
progress bars!

this is OK to merge. verified on a day of twitter in local hdfs...

Emilio let me know about the above comment. else i'll merge

**Comment by jahhulbert-ccri** [comment]
@vpipkt agrees:
20:41 < jbrown> lllooooolllllz progress bar [=====>         ] killing it

**Comment by vpipkt** [comment]
+1!!!1!

**Comment by jahhulbert-ccri** [comment]
bar

so cool but still not [=========>        ] quite there

**Comment by elahrvivaz** [comment]
haha, nice. Yeah, let's make a follow on ticket for showing progress to the user. I'll create one.

**Comment by elahrvivaz** [comment]
I've got some pretty baller progress bars going in another branch :D

**Comment by jahhulbert-ccri** [comment]
okkkkkk i'll let it slide and merge

**Comment by jahhulbert-ccri** [comment]
9b7309dcb5223420a27f4443263d5abde0d9df76

**Pull request closed without merging**
