### PR TITLE
GEOMESA-2584 Remove blobstore module

### PR DESCRIPTION
**Pull request by elahrvivaz**
* Moved to https://github.com/geomesa/geomesa-community

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
Should the upgrade guide mention this removal?

**Comment by elahrvivaz** [comment]
yes, thanks i'll add it.

**Comment by elahrvivaz** [comment]
added to upgrade guide

**Comment by jnh5y** [comment]
Merged as 970502c9c17ab1d0d797d78297ffccce2bac65b0

**Pull request closed without merging**
