### PR TITLE
Hbase 2.0.2 support for Geomesa

### PR DESCRIPTION
**Pull request by chrevanthreddy**
Added support for Hbase 2.0.2 and Hadoop 2.7. We have been using this successfully in Comcast production environment for 3 months now. The code does not support Visibility Labels yet.

### CODE REVIEW

**Comment by elahrvivaz** [comment]
@chrevanthreddy thanks for the contribution! I think we'll need to figure out some way to continue supporting hbase 1.4 (ideally at the same time), as that is the latest version offered by AWS EMR. It looks like the changes aren't too extensive - possibly we could have two distributed-runtime modules, one for 1.4 and one for 2.0.

**Comment by jnh5y** [comment]
@chrevanthreddy would you have some time to sign up for an Eclipse account and address the merge conflicts?

**Comment by chrevanthreddy** [comment]
@jnh5y Let me try to resubmit the pull request. will get it in by today

**Comment by chrevanthreddy** [comment]
@jnh5y @elahrvivaz Closing this pul request since the initial commits did not have sign off signature. Resubmitted the pull request

**Pull request closed without merging**
