### PR TITLE
GEOMESA-1292 Fixing assignment of geometry as an indexed attribute

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by cne1x** [comment]
This looks good to me.

One (small, probably irrelevant) question, though...  It looks like we have multiple places in the ```GeomAttributeSpec``` where we are working around the ```OPT_INDEX``` map entry.  What if we simply removed that up front from the ```options``` that are passed in?  If that entry is always Bad for this class, why not remove it?  Just a thought.

**Comment by elahrvivaz** [comment]
Yeah, I can see it both ways - there are multiple places that we construct the attribute spec from what i can see - figured it was safer to remove it at the end then try to catch it up front. Should probably do both for extra security...

**Comment by cne1x** [comment]
I hadn't realized there were multiple ways to get those options in.  In that case, forget I mentioned it.  :)

**Comment by jnh5y** [comment]
Does this PR handle the situation where an old table has geom:index=true already set?

**Comment by elahrvivaz** [comment]
@jnh5y yep

**Pull request merged**
