### PR TITLE
GEOMESA-3065 HBase - fix infinite loop caused by HBase meta errors

### PR DESCRIPTION
**Pull request by elahrvivaz**

### CODE REVIEW

**Comment by elahrvivaz** [comment]
we should probably back-port this

**Comment by elahrvivaz** [comment]
I tested this against the HBase instance that was exhibiting the issue, but it would be hard to unit test without exposing some private methods and using mock objects.

**Comment by elahrvivaz** [comment]
This fixed the infinite loop, but the export still eventually hung due to the inconsistencies in HBase causing scans to not work. Running `hbck` fixed the issue. So this is probably a good thing to merge, but back-porting it probably isn't necessary.

**Comment by jnh5y** [comment]
Hmm... when the export failed later, was it clear that there was an HBase issue?

**Comment by elahrvivaz** [comment]
> Hmm... when the export failed later, was it clear that there was an HBase issue?

I believe so, it was errors in the hbase scanner.next iirc

**Pull request merged**
