### PR TITLE
Updating release version to 2.0.2

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by elahrvivaz** [comment]
thanks, we actually need to also update build/README.md, or it will be overwritten every time you build. What is the email on your account? I'm trying to verify the eclipse CLA

**Comment by anitagraser** [comment]
I see. My email is anitagraser@gmx.at

**Comment by elahrvivaz** [comment]
Thanks, I can see your email if I pull your branch, but couldn't figure out how to view it on github :P 
You'll need to sign the Eclipse CLA, as outlined here: https://github.com/locationtech/geomesa/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by anitagraser** [comment]
Updating geomesa.release.version in the build/README.md means updating the pom.xml at https://github.com/locationtech/geomesa/blob/master/pom.xml#L62 as far as I can see, right?

**Comment by elahrvivaz** [comment]
yeah, you're correct - if you modify that, then run `mvn install -pl .` it should update the main README

**Comment by elahrvivaz** [comment]
thanks!

**Pull request merged**
