### PR TITLE
GEOMESA-846  Allowing for appending of attributes to simple features types with kryo encoding

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by anthonyccri** [comment]
@elahrvivaz  @BrittEvans  Do these appended attributes get persisted into the database or are they just ephemeral?  And if they're ephemeral, why wouldn't we put them in the userData hash map?  Presumably performance?

**Comment by elahrvivaz** [comment]
@anthonyccri They get persisted into the database when new features are written. The old features will have null values for the new attributes.

**Comment by anthonyccri** [comment]
@elahrvivaz Does this work out ok with indexes?

@jnh5y Does this address some of the requests we've had regarding mutable simple feature types?

**Comment by elahrvivaz** [comment]
@anthonyccri what do you mean by indices? Essentially, the kryo deserialization will work on the newly serialized features and the old serialized features.
As an addendum, I think we should deprecate support for avro encoding - we've made a lot of performance improvements that only works with kryo encoding that we could expand to use in more places if we don't have to worry about avro serialization.

**Comment by jnh5y** [comment]
@anthonyccri I haven't had a chance to read the PR yet.  I'd assume that this would make supporting modifySchema a slam-dunk.

**Comment by jahhulbert-ccri** [comment]
I'll add a modify schema command to the tools once it's in

**Comment by anthonyccri** [comment]
@jnh5y It's pretty close . . . though deleting an attribute doesn't exist.

**Comment by anthonyccri** [comment]
Ok, merging.

**Comment by elahrvivaz** [comment]
Actually, deleting attributes might work too... we'd have to test to make sure though. And adding then deleting (or vice versa) would probably screw it up.

**Pull request merged**
