### PR TITLE
GEOMESA-969 Fixing readme

### PR DESCRIPTION
**Pull request by jahhulbert-ccri**
Signed-off-by: Andrew Hulbert <andrew.hulbert@ccri.com>

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
@jdk2pq hopefully this is right

**Comment by jdk2pq** [comment]
perfect

**Comment by jdk2pq** [comment]
building should only change the readme when there's a release now.

**Comment by jahhulbert-ccri** [comment]
cool.

**Comment by jdk2pq** [comment]
Committed as b655edee477d5fbc5ba4e16e2809dcd814d0525d

**Pull request closed without merging**
