### PR TITLE
GEOMESA-1063 API for discovering available feature types and converters

### PR DESCRIPTION
**Pull request by anthonyccri**
* Added some methods for accessing feature types and converters that
  are available on the classpath
* All files name "geomesa-data.conf" on the classpath will be loaded.
* Each file is expected to have a root element ```geomesa.converters```
  with one key corresponding to the name of the data type.  Under the
  data type name should be ```sft``` and ```converter``` definitions.

Signed-off-by: Anthony Fox <anthonyfox@ccri.com>

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
FYI example confs here; https://github.com/locationtech/geomesa/blob/master/geomesa-tools/conf/application.conf

**Comment by anthonyccri** [comment]
@jahhulbert-ccri good catch.  Ok, seems like we need to do a bit of disambiguation.  @elahrvivaz check out https://github.com/geomesa/gm-data

I like the idea of having definitions in modular jar files available on the classpath.  Especially if we have the wrapper classes generated and dropped into those jars.  I think we also need the ability to load and modify definitions at runtime - not from the classpath.  Anyone have thoughts around this?

**Comment by jahhulbert-ccri** [comment]
We 100% need to load and modify while running in addition to the classpath so that we can support interactive type/converter creation without restarting the containers...

Currently we can do it via a separate jar file like this and reference them by name...which i'm going to probably change to include dropdown of known types.

https://github.com/jahhulbert-ccri/geomesa-nifi/tree/master/geomesa-nifi-resources/src/main/resources

nifi-geomesa1

**Comment by elahrvivaz** [comment]
We should be able to dynamically drop in jars on the classpath right now - you just have to have a file named application.conf in your jar, and we will pick it up with ConfigFactory.load:
https://github.com/typesafehub/config#standard-behavior

**Comment by elahrvivaz** [comment]
Also, I added a 'name' to converters, so we can match them up with the sft using that.

**Comment by elahrvivaz** [comment]
for runtime changes, we could use zookeeper distributed caching. we already have that mostly done in whiptail, hooked up to a rest api, but we could make it part of the command line tools instead.

**Comment by jahhulbert-ccri** [comment]
closing for additional work...copied branch here: https://github.com/jahhulbert-ccri/geomesa/tree/fcr_discover_api

**Pull request closed without merging**
