### PR TITLE
GEOMESA-1196 Setting of user data in converters

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
looks good. @elahrvivaz would you mind throwing in a new converter for example csv and json with the vis in user data here: https://github.com/locationtech/geomesa/tree/master/geomesa-tools/examples/ingest and/or here: https://github.com/locationtech/geomesa/blob/master/geomesa-tools/conf/application.conf so that I  can include multi level visibility in a simple scripted integration test?

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri will od

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri added examples. I ran it with (accumulo connection params omitted):
./geomesa ingest -s example-csv -C example-csv-with-visibilities ../examples/ingest/csv/example.csv

**Comment by jahhulbert-ccri** [comment]
@elahrvivaz awesome, I'm going to try to add that into some bash-script testing thanks. it's on the slate for today.

**Pull request merged**
