### PR TITLE
GEOMESA-1690 HBase Distributed Ingest Enabled and Tested

### PR DESCRIPTION
**Pull request by MutahirKazmi**
Signed-off-by: Mutahir <kazmi.mutahir@gmail.com>

Successfully tested ingest with HBase and Yarn. Fixed missing jar issues.

### CODE REVIEW

**Comment by elahrvivaz** [comment]
thanks! how did you distribute the hbase-site.xml file? Is that something we can document or facilitate?

**Comment by MutahirKazmi** [comment]
I made no changes to hbase-site.xml. It is the default without any configurations.

**Comment by elahrvivaz** [comment]
is your setup actually distributed? most people have run into issues where the hbase connection can't be instantiated in the mappers because the hbase-site.xml isn't on the hadoop distributed classpath. If you're running on a single node or something, this might not be an issue. I'm going to create a new ticket for this PR and leave the other ticket open until we can sort out the hbase-site.xml distribution.

**Comment by MutahirKazmi** [comment]
My setup has one namenode, one datanode, one nodemanager (yarn) and one resource manager (yarn). I don't have enough resources / computing power to test it with more than that.

**Pull request merged**
