### PR TITLE
WIP to support Spark 3.2.0.

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jhughes@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
Spark 3.2.0 does not have 2.11 artifacts...

**Comment by elahrvivaz** [comment]
i'm not sure that our build passes against spark 3.1 either, but the artifacts do work there...

**Comment by pashashiz** [comment]
Hello, we were using Geomesa with Spark 3.1, 3.2 and now with 3.3 for more than a year already. All works fine except for one issue with Databricks compatibility (I am going to propose a fix today). Any chance we can upgrade the spark to the latest 3.x version? Yet that will require dropping Scala 2.11 I suppose or we can play around with maven profiles and have different spark versions. If you need any help with that, please, let me know.

**Comment by elahrvivaz** [comment]
> Hello, we were using Geomesa with Spark 3.1, 3.2 and now with 3.3 for more than a year already. All works fine except for one issue with Databricks compatibility (I am going to propose a fix today). Any chance we can upgrade the spark to the latest 3.x version? Yet that will require dropping Scala 2.11 I suppose or we can play around with maven profiles and have different spark versions. If you need any help with that, please, let me know.

We are planning on bumping up our spark version with our next major release, which will come immediately following our pending 3.5.0 release. As you say, we've been holding back b/c it requires dropping scala 2.11 support. thanks!

**Pull request closed without merging**
