### PR TITLE
GEOMESA-2451 HBase - empty transform causes filter deserialization error

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
@elahrvivaz would it be possible to add a quick Spark SQL test for this?  That's where this came up initially, right?

**Comment by elahrvivaz** [comment]
@jnh5y we don't currently have any spark sql hbase tests... I believe you added an integration-style test that gets skipped by default, do you know if there's a reason we don't have any other ones?

**Comment by jnh5y** [comment]
@elahrvivaz doesn't https://github.com/locationtech/geomesa/blob/master/geomesa-hbase/geomesa-hbase-spark-runtime/src/test/scala/org/locationtech/geomesa/hbase/spark/HBaseSparkProviderIntegrationTest.scala run during the build?

Maybe I'm making things up...

**Comment by elahrvivaz** [comment]
@jnh5y it does run but all the tests have `skipped` in them

**Comment by elahrvivaz** [comment]
This fixes the one problem but the spark sql count operation still isn't working - I think we could merge this one and then open a new ticket for spark

**Comment by elahrvivaz** [comment]
Ok, finally tracked down the bug `Filter.isFamilyEssential` needs to be true not false. This doesn't seem to matter in the embedded hbase, but does in an actual hbase instance.

**Pull request merged**
