### PR TITLE
GEOMESA-1747 Arrow geometry vectors, Arrow-based data store

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
uses a snapshot build of arrow - will update to 0.3 once it's released and available in maven central.

**Comment by anthonyccri** [comment]
Looks great.  I'm happy to merge now or wait until a few more bits of functionality.  Additional things we need: command line tools, WFS mime/type, iterator push-down. What do you think?

**Comment by elahrvivaz** [comment]
I'd say merge this so the PR doesn't become too huge. I've got the iterator push-down queued up, but I was waiting for this PR first.

**Comment by elahrvivaz** [comment]
It is going to break master though, since it requires an arrow snapshot

**Comment by elahrvivaz** [comment]
they're looking at a release in the next 2 weeks possibly. Given that, I'll just keep stacking PRs for now I guess

**Comment by elahrvivaz** [comment]
replacing with #1457

**Pull request closed without merging**
