### PR TITLE
GEOMESA-3162: Geomesa client configuration file properly loaded (3.2 backport)

### PR DESCRIPTION
**Pull request by jgibson**
The fix for GEOMESA-3162 on the 3.2.x branch, see #2824 for details.

### CODE REVIEW

**Comment by jgibson** [comment]
I'm guessing that these builds are stuck in an infinite loop or something because it's been 5+ hours and no output for the unit test stage.

**Comment by jgibson** [comment]
Now that I can see the logs it looks like things just got stuck at the Accumulo tests. That happened once to me on my laptop when I was running tests on the 3.1.x branch while on WiFi as opposed to a wired connection. I assumed that it was just my local environment, but perhaps it's an issue with the transient Accumulo cluster that gets created for testing purposes or something.

**Comment by elahrvivaz** [comment]
yeah the github actions tend to fail intermittently. I'll kick them again to try to get them passing. thanks!

**Comment by elahrvivaz** [comment]
i'll merge these once the builds all pass

**Pull request merged**
