### PR TITLE
GEOMESA-3162: Geomesa client configuration file properly loaded (3.3 backport)

### PR DESCRIPTION
**Pull request by jgibson**
The fix for GEOMESA-3162 on the 3.3.x branch, see #2824 for details.

### CODE REVIEW

**Comment by elahrvivaz** [comment]
ah, thanks for doing all the other branches!

**Comment by jgibson** [comment]
I'm not sure why `AccumuloExportCommandTest` failed. It worked in my local checkout when I ran it by itself against both 2.11 and 2.12 versions of the code.

**Comment by elahrvivaz** [comment]
build works for me locally.

**Comment by elahrvivaz** [comment]
actions keeps failing, but i verified the build locally.

**Pull request merged**
