### PR TITLE
GEOMESA-2931 - Upgrade to GeoTools version 23.3

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
do we need any cqs for this?

**Comment by jnh5y** [comment]
> do we need any cqs for this?

I view the GT and Jai-ext releases as bug fixes.  As such, I think the current CQs cover them.  If you disagree, lemme know and I'll enter the CQs.

**Comment by elahrvivaz** [comment]
fixed up merge as c22fb876a8a8233c85451f226da5dbad0589344a

**Comment by elahrvivaz** [comment]
we should probably bump in geomesa-nifi and geomesa-geoserver too, unless they inherit from this...

**Pull request merged**
