### PR TITLE
GEOMESA-2703 Write GeoMesa Filesystem on Azure Tutorial

### PR DESCRIPTION
**Pull request by jrs53**
Adding docs with associated images. Requires corresponding commit to
geomesa-tutorials repo for notebook.

Signed-off-by: James Srinivasan <james.srinivasan@gmail.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
@jrs53 this looks great!  Any chance you can reduce the size of the PNGs?  One of them is over a meg and quick large.  We can probably skip on the Ultra 8k resolution:).

Of course, I'm setting myself up for GeoMesa not being in high-def...

**Comment by jrs53** [comment]
Cropped & resampled image - was originally 4k which is probably rather overkill... Now file size is similar to complex images in other tutorials

**Comment by jrs53** [comment]
Pretty sure the Travis failures ain't me...

**Comment by elahrvivaz** [comment]
kicked travis

**Comment by elahrvivaz** [comment]
I ran the docs build and verified that there are no syntax errors

**Pull request merged**
