### PR TITLE
1.2 - GEOMESA-1448 Fixing explain logger configs

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
@elahrvivaz, @anthonyccri would note that he has some scripts which assume that commit titles are GEOMESA-####.  It is silly, but mind moving the '1.2' to the end of the line (or removing it)?

**Comment by elahrvivaz** [comment]
@jnh5y the commit message doesn't have the 1.2, just the title of the PR.

**Comment by jnh5y** [comment]
@elahrvivaz Ah!  Excellent!

**Comment by mdzimmerman** [comment]
Does this change need to be backported to the 1.2.6 docs?

**Comment by elahrvivaz** [comment]
@mdzimmerman do you mean to update the web site? that would be great!

**Pull request merged**
