### PR TITLE
GEOMESA-2804 Upgrade to SFCurve 0.2.2

### PR DESCRIPTION
**Pull request by jnh5y**
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
I started a WIP branch a while ago and added a couple unit tests here that might be worth pulling in: https://github.com/elahrvivaz/geomesa/commit/5a800702c9b713e186848fb85e503cdc66696ab2

**Comment by elahrvivaz** [comment]
I went ahead and added them to the branch.

**Comment by elahrvivaz** [comment]
merged as c97e19c6cd8163bc9be7d8bd3a3590345f492b0d

**Comment by jnh5y** [comment]
@elahrvivaz thanks for merging!

**Pull request closed without merging**
