### PR TITLE
GEOMESA-1360 Accounting for error rates in attribute equals count estimation

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz elahrvivaz@ccri.com

### CODE REVIEW

**Comment by elahrvivaz** [comment]
@jahhulbert-ccri can you check this out with the queries from the ticket?

**Comment by jahhulbert-ccri** [comment]
@elahrvivaz ya i'll check it out

**Comment by jahhulbert-ccri** [comment]
looks good

**Comment by jahhulbert-ccri** [comment]
@elahrvivaz i don't think we'll ever get to test this the way we desired... Perhaps its best to put it on 1.3.3 or 1.4.x and go from there?

**Comment by elahrvivaz** [comment]
sounds good

**Comment by jahhulbert-ccri** [comment]
@jnh5y do you want to look this over else we'll give it a merge

**Comment by jnh5y** [comment]
@jahhulbert-ccri if you are happy with it, let's merge it!

**Pull request merged**
