### PR TITLE
GEOMESA-2112 HBase CLI incremental load

### PR DESCRIPTION
**Pull request by elahrvivaz**
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
note: this will cause compile conflicts with #1848 - need to add the `--no-remote-filters` flag to the new bulk load command params

**Comment by elahrvivaz** [comment]
added docs - will still need a merge with #1848 once that is merged

**Comment by jahhulbert-ccri** [comment]
@elahrvivaz  ready for rebase

**Comment by elahrvivaz** [comment]
rebased

**Pull request merged**
