### PR TITLE
Added SIGINT handling for geomesa-fs commands

### PR DESCRIPTION
**Pull request by aheyne**
Signed-off-by: Austin Heyne <aheyne@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
i'm not sure about this... @jahhulbert-ccri what do you think?

**Comment by aheyne** [comment]
I can agree, I think the real solution would be to:
A. Add a reduce task that does what the driver program does. 
B. Make it so driver program can recover/re-attach
C. Keep more metadata around so all this isn't necessary.

**Comment by jahhulbert-ccri** [comment]
yeah I would rather not have any custom trapping in bash...what was the problem again? The metadata is corrupted because of the job? I think we keep extra metadata around we can roll it back?

**Comment by aheyne** [comment]
The list of files that were compacted and need deleted is kept in memory meaning if the driver program is killed then it never gets removed and the metadata never gets updated.

**Comment by elahrvivaz** [comment]
I'm going to close this - created a ticket to track the underlying issue here: https://geomesa.atlassian.net/browse/GEOMESA-2162

**Pull request closed without merging**
