### PR TITLE
GEOMESA-1203 VisibilityFilter's cache should be thread safe

### PR DESCRIPTION
**Pull request by ddseapy**
Signed-off-by: David Seapy <ddseapy@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
looks good to me

**Comment by jahhulbert-ccri** [comment]
looks good...lets hope they don't find more of these: https://issues.scala-lang.org/browse/SI-7943

#java.util.concurrent.ConcurrentHashMap :coffee:

**Comment by ddseapy** [comment]
Yeah, originally I tried going with a ConcurrentHashMap, but I'd have to write some sort of wrapper around it since id have to use "putIfAbsent" instead of "getOrElseUpdate" because it doesn't allow the lazy evaluation of the passed value (defeating the purpose of using the vizcache). This approach seemed easier.

**Comment by elahrvivaz** [comment]
merging

**Comment by elahrvivaz** [comment]
f4e84a0fc66bb2f892d2ecbeb0c0071296dfda58

**Pull request closed without merging**
