### PR TITLE
GEOMESA-1300 Data jar with just converter and sft definitions

### PR DESCRIPTION
**Pull request by elahrvivaz**
* Available as artifactId 'geomesa-tools_${scala.binary.version}' with classifier 'data'

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

### CODE REVIEW

**Comment by elahrvivaz** [comment]
you can, you just have to import it in the geomesa-tools/conf/reference.conf. Is that ok?

**Comment by jnh5y** [comment]
Is there anyway to avoid the two step process to add sft confs?

**Comment by elahrvivaz** [comment]
yeah, you can just put the file at the top-level of the conf dir. I wanted to keep the classloading in the tools in sync with the jar - otherwise I figured that someone would add a new sft but forget to add it to the jar. But we can also roll back to just searching for sft folders in the conf file.

**Comment by jnh5y** [comment]
I wonder if anyone is using the ability to add SFTs, etc.  

Could we split the difference?  Load up the jar and search the conf directory structures?

**Comment by elahrvivaz** [comment]
yeah, i kept the existing ones in conf instead of a jar to make it easier to edit them if desired. but I could include the jar instead

**Comment by jnh5y** [comment]
Ok, do we already have a tutorial/other documentation on what the GeoMesa converters do?  Maybe we should update that and explain how things change?  @mdzimmerman thoughts?

**Comment by mdzimmerman** [comment]
There is not a tutorial. There is, however, a chapter on the converters library in ``docs/user/convert.rst`` (http://www.geomesa.org/documentation/current/user/convert.html) which I think would be the appropriate place to describe the changes.

**Comment by elahrvivaz** [comment]
I'll update the docs - @jahhulbert-ccri @jnh5y are we satisfied with the current behavior?

**Comment by mdzimmerman** [comment]
In the final section ("Loading Converters and SFTs at Runtime"), there's a reference to gm-data that should probably be removed.

**Comment by jnh5y** [comment]
@elahrvivaz I think the behavior in this PR is sensible.  My main push is to document it.

**Comment by elahrvivaz** [comment]
updated docs

**Pull request merged**
