### PR TITLE
Fix for GEOMESA-3182

### PR DESCRIPTION
**Pull request by kronster**
Fixed https://geomesa.atlassian.net/browse/GEOMESA-3182

Corrected the version check so the Jute jar is installed.

### CODE REVIEW

**Comment by elahrvivaz** [comment]
Thanks for fixing this! Before I merge, could you sign the eclipse contributor agreement to ensure that our apache license is maintained? thanks again! https://github.com/locationtech/geomesa/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by kronster** [comment]
Signed.

**Review by kronster — COMMENTED** [review]
oops.  good catch.

**Review by elahrvivaz — APPROVED** [review]

**Comment by elahrvivaz** [comment]
thanks again!

**Comment by kronster** [comment]
Sure thing.. You've been so helpful, the least I could do is return the favour.I do have a couple of further questions I'm saving up too.. ;) On 8 Mar 2022 12:43 am, Emilio ***@***.***> wrote:
Thanks for fixing this! Before I merge, could you sign the eclipse contributor agreement to ensure that our apache license is maintained? thanks again! https://github.com/locationtech/geomesa/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement

**Pull request merged**
