### PR TITLE
GEOMESA-1296 Sphinx documentation should support the 'singlehtml' bui…

### PR DESCRIPTION
**Pull request by cne1x**
…ld option

In the event that anyone wants a single-page build of all three manuals.

Signed-off-by: Chris Eichelberger <cne1x@ccri.com>

### CODE REVIEW

**Comment by mdzimmerman** [comment]
Looks good to me!

**Comment by cne1x** [comment]
@jnh5y Can I get a push-button merge for this?  Matt's already given it his blessing as the Keeper of the Docs; he just doesn't have permission to merge.  Thanks!

**Comment by jnh5y** [comment]
@cne1x bad news...  there are merge conflicts.  Fix 'em, and yes, I'll merge!

**Comment by cne1x** [comment]
Fixed, yo.

**Pull request merged**
