### PR TITLE
GEOMESA-1983 Shade deps per datastore

### PR DESCRIPTION
**Pull request by jahhulbert-ccri**

### CODE REVIEW

**Comment by elahrvivaz** [comment]
should we shade bigtable too?

**Comment by jahhulbert-ccri** [comment]
i think i shaded it as hbase...but maybe it should be separate?

**Comment by elahrvivaz** [comment]
oh didn't notice - i guess let's make it `bigtable` to be consistent

**Comment by jahhulbert-ccri** [comment]
cool i switched it over

**Pull request merged**
